import torch
import numpy as np
from deeprx_model import DeepRx

def info(model: torch.nn.Module) -> list:
    """
    Retrieve and summarize information about a PyTorch model.
    
    Args:
        model (torch.nn.Module): The PyTorch model for which information is to be retrieved.
    
    Returns:
        list: A list containing detailed information about the model, including:
              - Total number of learnable parameters.
              - Unique layer names present in the model.
              - The device on which the model is located (e.g., 'cpu' or 'cuda').
    """
    total_learnables = sum(p.numel() for p in model.parameters() if p.requires_grad)
    unique_layers = [name.split('.')[0] for name, module in model.named_modules()]
    is_cuda = next(model.parameters()).is_cuda if model.parameters() else False
    return total_learnables, unique_layers, is_cuda

def select_device():
    """
    Selects and returns the most appropriate PyTorch device for computations.

    This function checks if CUDA is available and returns a CUDA device if so.
    If CUDA is not available, it defaults to returning a CPU device.

    Returns:
        torch.device: The selected device for PyTorch operations.
    """
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")

def construct_model(in_size: int, out_size: int, model_path: str = None) -> torch.nn.Module:
    """
    Constructs and optionally loads a DeepRx model.

    This function initializes a DeepRx model with given input and output sizes and 
    optionally loads pre-trained weights from a specified file path.

    Args:
        in_size (int): The size of the input layer.
        out_size (int): The size of the output layer.
        model_path (str, optional): Path to the file containing the model weights. 
            If provided, the function will load the weights from this file.

    Returns:
        torch.nn.Module: An instance of the DeepRx model, with weights loaded if a 
        model path is provided.
    """
    # Determine the device
    device = select_device()

    # Create an instance of the DeepRx model
    model = DeepRx(in_size, out_size)

    # Load the model weights if a path is provided
    if model_path:
        model.load_state_dict(torch.load(model_path, weights_only=True, map_location=device))
    return model

def predict(model: torch.nn.Module, x_test: np.ndarray) -> np.ndarray:
    """
    Generate LLR predictions from a PyTorch model for the given test data.
    
    This function takes a trained PyTorch model and a NumPy array of test data as input,
    and returns the model's predictions as a NumPy array. The function handles the conversion
    of input data to PyTorch tensors and ensures that the model is in evaluation mode.
    
    Args:
        model (torch.nn.Module): The trained PyTorch model used for making predictions.
        x_test (np.ndarray): A NumPy array containing the test data. The data should be 
                             preprocessed and shaped appropriately for the model.
    
    Returns:
        np.ndarray: A NumPy array containing the predictions generated by the model.
    """
    # Determine the device
    device = select_device()

    # (MATLAB-PyTorch Compatibility) Reshape test resource grid: [F S 4*N_rx+2] -> [1 4*N_rx+2 F S]
    x_test_tensor = torch.tensor(x_test, dtype=torch.float32)
    x_test_tensor = torch.unsqueeze(x_test_tensor, 3)
    x_test_tensor = torch.permute(x_test_tensor, (3, 2, 0, 1)).to(device)

    with torch.no_grad():
        # Perform forward pass and get predictions
        y_pred = model(x_test_tensor)

        # (MATLAB-PyTorch compatibility) Reshape predicted LLRs: [1 4*N_rx+2 F S] -> [F S 4*N_rx+2 1]
        L = torch.permute(y_pred, (2, 3, 1, 0))
        L = torch.squeeze(L).contiguous().detach().cpu().numpy()
    return L